var MERITS = [
["Aute Sense", 1],
["Alcohol Tolerance", 1],
["Ambidextrous", 1],
["Double-Jointed", 1],
["Mixed-Morph", 5],
["Perfect Balance", 1],
["Wolf Sight", 1],
["Bad Taste", 2],
["Fair Glabro", 2],
["Lack of Scent", 2],
["Physically Impressive", 2],
["Daredevil", 3],
["Long-Distance Runner", 3],
["Natural Weapons", 3],
["Huge Size", 4],
["Metamorph", 7],
["Common Sense", 1],
["Computer Aptitude", 1],
["Concentration", 1],
["Expert Driver", 1],
["Language", 1],
["Lightning Calculator", 1],
["Mechanical Aptitude", 1]
["Time Sense", 1],
["Berserker", 2],
["Code of Honor", 2],
["Eidetic Memory", 2],
["Inner Strength", 2],
["Natural Linguist", 2],
["Seldom Sleeps",2],
["Calm Heart", 3],
["Iron Will", 3],
["Jack-Of-All-Trades", 3],
["Self-Confident", 5],
["Untamable", 5],
["Family Support", 1],
["Favor", 3],
["Pitiable", 1],
["Camp Goodwill", 1],
["Animal Magnetism", 2],
["Natural Leader", 2],
["Notable Heritage", 2],
["Reputation", 2],
["Supporter", 2],
["Noted Messenger", 3],
["Supernatural Companion", 3],
["Ancestor Ally", 1],
["Moon-Bound", 1],
["Spirit Magnet", 1],
["Danger Sense", 3],
["Lucky", 3],
["Natural Channel", 3],
["True Love", 4],
["Immune to Wyrm Emanations", 6],
["Silver Tolerance", 7]
];

var FLAWS = [
["Animal Musk", 1],
["Anosmia", 1],
["Hard of Hearing", 1],
["Monochrome Vision", 1],
["No Partial Transformation", 1]
["Short", 1],
["Strict Carnivore", 1],
["One Eye", 2],
["Bad Sight", 3],
["Deformity", 3],
["Double Jeopardy", 3],
["Lame", 3],
["Monstrous", 3],
["One Arm", 3],
["Deaf", 4],
["Mute", 4],
["Blind", 6],
["Compulsion", 1],
["Impatient", 1],
["Intolerance", 1],
["Nightmares", 1],
["Overconfident", 1],
["Shy", 1],
["Soft-Hearted", 1],
["Speech Impediment", 1],
["Amnesia", 2],
["Curiosity", 2],
["Pack Mentality", 2],
["Phobia", 3],
["Short Fuse", 2],
["Territorial", 2],
["Vengeful", 2],
["Absent-Minded", 3],
["Deranged", 3],
["Driving Goal", 3],
["Hatred", 3],
["Weak Willed", 3],
["Ability Deficit", 5],
["Flashbacks", 6],
["Conniver", 1],
["Dark Secret", 1],
["Enemy", 5],
["Naive", 1],
["Twisted Upbringing", 1],
["Camp Enmity", 1],
["Gullible", 2],
["Persistent Parents", 2],
["Notoriety", 3],
["Ward", 3],
["Hunted", 4],
["Metis Child", 4],
["Banned Transformation", 6],
["Cursed", 5],
["Foe from the Past", 3],
["Forced Transformation", 2],
["Insane Ancestor", 1],
["Slip Sideways", 1],
["Docile", 3],
["Mark of the Predator", 2],
["Sign of the Wolf", 2],
["Pierced Veil", 3],
["Harano Prone", 4],
["Dark Fate", 5],
["Taint of Corruption", 7]
];

var DERANGEMENTS = [
  ["Fugue"],
  ["Hysteria"],
  ["Multiple Personalities"],
  ["Obsessive-Compulsive"],
  ["Paranoia"],
  ["Schizophrenia"] 
];
